name: circular_slider
description: "A circular slider for Flutter with customizable segments, markers, and notches."
version: 0.1.0
homepage: https://github.com/nikhilbawane/circular_slider
repository: https://github.com/nikhilbawane/circular_slider

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: